test_suite_config:
  files:
  - path: ${PYTORCH_ROOT}/test/inductor/test_decompose_mem_bound_mm.py
    unlisted_test_mode: skip
    tests:
    - names:
      - TestDecomposeMemMM::test_decompose_bmm_cpu
      mode: mandatory_success
      tags:
      - inductor
      edits:
        dtypes:
          include:
          - name: float16
    - names:
      - TestDecomposeMemMM::test_dynamic_shape_decompose_addmm
      mode: mandatory_success
      tags:
      - inductor
      edits:
        dtypes:
          include:
          - name: float16
    - names:
      - TestDecomposeMemMM::test_decompose_mm_cpu
      mode: mandatory_success
      tags:
      - inductor
      - fp16
      edits:
        dtypes:
          include:
          - name: float16
          - name: float32
          exclude:
          - name: bfloat16
            description: Not supported on Spyre
  global:
    devices:
    - spyre
    supported_dtypes:
    - name: float16
    - name: float32
    supported_ops: []
